apiVersion: 1

datasources:
  - name: MeteoPostgreSQL
    type: postgres
    uid: meteo-postgres
    url: postgres:5432
    database: meteo_db
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: false
